apiVersion: v1
kind: Secret
metadata:
  name: yolo-secrets
  namespace: yolo
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "CHANGEME_user"
  MONGO_ROOT_PASSWORD: "CHANGEME_pass"
  JWT_SECRET: "CHANGEME_secret"
