apiVersion: v1
kind: Secret
metadata:
  name: yolo-secrets
  namespace: yolo
type: Opaque
stringData:
  # Update these values with your own secrets
  MONGO_ROOT_USERNAME: "user"
  MONGO_ROOT_PASSWORD: "pass"
  JWT_SECRET: "long_random"
