apiVersion: v1
kind: Secret
metadata:
  name: yolo-secrets
  namespace: yolo
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "admin123"
  JWT_SECRET: "supersecretjwtkey"
