apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-backend-config
  namespace: yolo
data:
  PORT: "5000"
  # Service DNS for Mongo headless service defined below
  MONGO_URL: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongo-0.mongo.yolo.svc.cluster.local:27017/yolo?authSource=admin"
  CLIENT_ORIGIN: "http://CHANGEME_PUBLIC_IP_OR_DOMAIN"
