apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-backend-config
  namespace: yolo
data:
  PORT: "5000"

  MONGO_URI: "mongodb://root:pmc123@mongo-0.mongo.yolo.svc.cluster.local:27017,mongo-1.mongo.yolo.svc.cluster.local:27017,mongo-2.mongo.yolo.svc.cluster.local:27017/yolomy?replicaSet=rs0&authSource=admin"

  CLIENT_ORIGIN: "http://34.35.137.242"
