apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-backend-config
  namespace: yolo
data:
  PORT: "5000"
  # MONGO_URL: "mongodb://mongo-0.mongo.yolo.svc.cluster.local:27017/yolo?authSource=admin"
  MONGO_URI: "mongodb://mongo-0.mongo.yolo.svc.cluster.local:27017/yolomy"

  CLIENT_ORIGIN: "http://<your-frontend-ip-or-domain>"
