apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: docker.io/pmcmuchiri/pmc-yolo-backend:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yolo-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yolo-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/yolo"  # Updated to use service name
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/yolo"  # Updated to use service name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: yolo-backend-config
                  key: PORT
            - name: CLIENT_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: yolo-backend-config
                  key: CLIENT_ORIGIN
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"