apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
  namespace: yolo
spec:
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
