apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: docker.io/pmcmuchiri/pmc-yolo-client:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_URL
              value: "http://yolo-backend:5000"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  selector:
    app: yolo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
