apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: docker.io/pmcmuchiri/pmc-yolo-client:v1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CLIENT_API_URL
              value: "http://34.35.131.113:5000"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
