apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: frontend
          image: pmcmuchiri/pmc-yolo-client:v1.0.1
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  selector:
    app: yolo-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
