apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
  namespace: yolo
spec:
  selector:
    app: yolo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

